CXX = g++
CXXFLAGS = -coverage -DMM3D_EDIT -I../../libmm3d -I../../implui -I../common -I../../../ -I/usr/include/qt4 -Wall -g
LFLAGS = -lQtTest -lQtCore -lQtGui -Wall -g -lGL -lGLU

.cc.o:
	g++ $(CXXFLAGS) -c $<

.cc.unit:
	g++ $(CXXFLAGS) $(LFLAGS) -o $*.unit $< ../../implui/qttex.o $(LIB) -lgcov

.cc.moc:
	moc-qt4 $< > $*.moc

.SUFFIXES: .cc .o .moc
.SUFFIXES: .cc .o .moc .unit .prof
.PHONY: all test check clean
