name: Build
on: [push, pull_request]

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # This is needed for "git describe" to work.
    - name: Install Dependencies
      run: |
        brew install autoconf automake qt@5
    - name: Configure
      continue-on-error: true
      run: |
        qt_version=$(ls -1 /usr/local/Cellar/qt@5 | sort -rV | head -1)
        ./autogen.sh
        ./configure --with-Qt-dir=/usr/local/Cellar/qt@5/${qt_version}
        # TODO --with-macosx-version-min=10.13
        echo "Qt: $(qt_version)"
        echo "print /usr/local/Cellar/qt@5"
        ls -l /usr/local/Cellar/qt@5
        echo "print /usr/local/Cellar/qt@5/$(qt_version)"
        ls -l /usr/local/Cellar/qt@5/$(qt_version)
        echo "print /usr/local/Cellar/qt@5/$(qt_version)/*"
        ls -l /usr/local/Cellar/qt@5/$(qt_version)/*
        echo "print config.log"
        cat config.log
    - name: make
      run: make
    - name: make appbundle
      run: make appbundle
    - name: Zip
      run: |
        zip -yr mm3d-$(git describe|sed 's/^v\([0-9]\)/\1/')-macos.zip "Maverick Model 3D.app"
    - uses: actions/upload-artifact@v2
      with:
        name: MacOS App
        path: ./mm3d-$(git describe|sed 's/^v\([0-9]\)/\1/')-macos.zip
